### ISSUE TITLE
Верстка

### ISSUE THREAD

**Issue by kolobai** [nsedenkov/mmaster_study#1]
Необходимо сверстать главную страницу для будущего интернет магазина. 
На данном этапе без интерактива (использования javascript). Основные требования к верстке: 
- кроссбраузерность, верстка должна поддерживать две последние десктопные версии популярных браузеров 
- использование html5 и css3 по максимуму.

Ссылка на дизайн: https://cloud.mail.ru/public/5oXJ/9aMbyJDjj

**Comment by nsedenkov** [comment]
Принято!

**Comment by nsedenkov** [comment]
Иван, макет имеет ширину 1300px. На моем экране 1280х1024 есть полоса прокрутки. Как полагаешь, может сразу следует задать диапазон примерно от 1200 до 1600? Думаю, "фоновая" барышня вполне себе растянется на +300 точек, а колонкам верхней строки задать ширину в процентах.

**Comment by kolobai** [comment]
Николай, ширина как правило задается дизайнером в зависимости от поставленной ему задачи и здесь ни чего додумывать не нужно. В нашем случае у нас один макет под определенную ширину, значит верстаем так как есть.

**Comment by nsedenkov** [comment]
Спасибо, понял

**Comment by kolobai** [comment]
Возможно будет удобнее при верстке использовать методологию БЭМ https://ru.bem.info/methodology/key-concepts/,  в частности соглашение по именованию https://ru.bem.info/methodology/naming-convention/
Почитай, попробуй.

**Comment by nsedenkov** [comment]
Спасибо, обязательно изучу.
Скажи, Иван, а чем ты производишь нарезку psd на отдельные элементы? Я погуглил - попадаются видеоуроки вроде "выделите слой, нажмите мышкой тут ... и т.д." Я замучился "нажимать мышкой" и написал небольшой скрипт (требует psd_tools /pip install psd_tools/, которые в свою очередь "хотят" Pillow), положил в ветку master в tools/psd - вдруг не только мне будет полезен

**Comment by kolobai** [comment]
> Скажи, Иван, а чем ты производишь нарезку psd на отдельные элементы?

Обычно ручками, безо всякой автоматизации. Верстать разработчику страницу полностью не так часто приходится (даже не помню когда последний раз это делал), в основном нужно вносить какие-то небольшие изменения. Но у верстальщиков, которые сталкиваются с этим каждый день, определенно есть свой набор инструментов, и если этот вариант работает, то тоже имеет право на существование, почему бы и нет.

**Comment by kolobai** [comment]
Николай, как напиши тогда как можно будет посмотреть результат.

**Comment by nsedenkov** [comment]
Иван, вот вроде удалось "добить" главную страницу со всеми прозрачными масками и т.п. Остался один вопрос (то есть, из того, что видно мне): в chrome все гладко, а вот firefox оставляет после футера большой пустой хвост. F12 нажимал, смотрел - элементы body и html заканчиваются сразу после футера. Хвост действительно пустой. Не соображу, как его убрать. Если можно, поясни пожалуйста. Спасибо.

**Comment by kolobai** [comment]
Что я например заметил глядя на дизайн:

1. Блок "Featured Items" в дизайне судя по направляющим был явно не на месте и сдвинут влево. Исправил, можешь по новой скачать psd файл.
2. Ширина дизайна 1300px (это ты подметил) и это ширина фоновых изображений, т.е. максимальная ширина. Тогда минимальная же ширина, судя по все тем же направляющим, 1140px http://joxi.ru/Y2L8G3MunzeBe2.

Текущий результат верстки мало соответствует дизайну http://joxi.ru/MAjRXyQFvDZWvA, согласись. Но это и понятно, ты же только начал обучатся, так что, давай заново и по пунктам (наверняка тогда твоя проблема с футером решится сама собой).

Для начал сделай вот что:

1. каркас страницы с необходимой максимальной и минимальной шириной
2. хедер (лого, меню, малая корзина и пока только ссылка на профиль)
3. баннер (фото с барышней)

Значит пока я от тебя жду три коммита, по этим трем пунктам.

PS не забывай в комментарии к коммиту указывать привязку к задаче, чтобы они были в ленте переписки по задаче http://joxi.ru/KAxgEvxC4Dq752

**Comment by nsedenkov** [comment]
Смещение Featured я конечно видел - и "бережно" воспроизвел. Думал, это не баг, а фича. Ну да ладно. Сейчас мне гораздо интереснее про направляющие (на самом деле я впервые в жизни вижу файл psd и потому могу задавать дурацкие вопросы). Я понял, что крайние вертикальные задают минимум ширины, причем по второй от края линии. Это общепринято? То есть, видя такую разграфку, можно понимать именно так и уже не уточнять, это ли имелось в виду? Далее: как с направляющими взаимодействовать? Может, существует способ быстро узнавать координаты линий кроме "глазками по линеечке"? И еще: есть ли ограничения по версии Фотошопа для наших макетов? Дело в том, что у меня в VirtualBox есть WinXP и там установлен Photoshop 8.0 (2003 года выпуска), он их читать отказывается, точнее пытается, но не может. Поэтому я работаю с GIMPом на хост-машине в Дебиане.

**Comment by kolobai** [comment]
> Я понял, что крайние вертикальные задают минимум ширины, причем по второй от края линии. Это общепринято?

Нет, это не общепринято, но здесь это явно. 

> Может, существует способ быстро узнавать координаты линий кроме "глазками по линеечке"?

В фотошопе есть инструмент линейка, кроме него, пожалуй, ни чего.

> И еще: есть ли ограничения по версии Фотошопа для наших макетов?

GIMP порой, а точнее даже как правило, открывает psd файлы с искажениями. Ограничений по фотошопу быть не должно, где-то у меня был старый фотошоп, проверю.

Видео уроки по версте https://www.youtube.com/playlist?list=PLcVuGt1dXgc11SafdJPBnr4dQhl5SdWey

**Comment by nsedenkov** [comment]
>GIMP порой, а точнее даже как правило, открывает psd файлы с искажениями

Иван, ты совершенно прав! Вот, что мне показал GIMP:
 [http://joxi.ru/L21WXGeCL5b4rX](http://joxi.ru/L21WXGeCL5b4rX)
Собственно, так я и "наверстал". Что ж, буду знать. Накопал в "закромах" фотошоп 9, открыл файл, теперь вижу, как должно быть. Полагаю, 2й "заход" будет удачнее. Работаем дальше.

**Comment by nsedenkov** [comment]
Иван, и сразу еще вопрос. Вот такое поведение при открытии файла фотошопом:
[http://joxi.ru/LmGy5nQinQaKAl](http://joxi.ru/LmGy5nQinQaKAl)
это нормально? Он так почти на каждый слой ругается. Потом все-таки открывает, но еще отмечает следующее: "Some text layers contain fonts that are missing..." Как узнать, какой именно фонт он ищет? Ведь может оказаться, что в результате этого я и текст вижу в ином виде, чем задумал дизайнер.

**Comment by kolobai** [comment]
Такие слои помечаются в палитре слоев. Узнать необходимый шрифт можно кликнув на текст в режиме редактирования или дважды кликнув на слой.
http://joxi.ru/DrlEk86S4DRx6m

**Comment by nsedenkov** [comment]
Иван, если будет возможность, взгляни пожалуйста: на странице Product detail в PSD уменьшенные изображения смещены вверх-вниз. Я так рассудил, что в данном месте планируется js-плагин галерея и изображения должны быть разными. В свойство background их "зашивать" нельзя. Поэтому тут я не стал воспроизводить картинку из PSD дословно. Я прав?

**Comment by kolobai** [comment]
> Необходимо сверстать главную страницу для будущего интернет магазина. 

Цель была получить базовые навыки верстки и на данном этапе одной страницы достаточно. Главная готова, можно смотреть?

**Comment by nsedenkov** [comment]
Да! Я что-то похоже переусердствовал! Готовы главная (5 дней назад), а также grid, list, detail и немного осталось доделать корзину. Честно, я думал, мои коммиты с комментариями и есть отчет о готовности.

**Comment by kolobai** [comment]
Проверь на соответсвие дизайну и кроссбраузерность.

**Comment by nsedenkov** [comment]
По кроссбраузерности могу доложить следующее: Chrome 50, Firefox 43, Iceweasel 38 (версия Firefox для Debian, т.е текущий FF - 5), а также Opera 36 отображают верстку одинаково (насколько я могу судить на глаз). К сожалению, Safari мне не доступен, так что тут ничего утверждать не могу (буду признателен за любой совет). Что касается соответствия дизайну - вычитал такой способ: сделать скриншот, поместить в psd в качестве отдельного слоя, установить прозрачность и так сравнить. Попробую.

**Comment by nsedenkov** [comment]
Иван, спасибо за отличную идею по поводу соответствия дизайну! Сразу скажу, фотошоп для меня темный лес и связываться с ним я не стал. Фактически, все, что у меня хорошо получается в фотошопе - это переводить изображения в битовый формат (еще могу делать дроплеты и оборачивать их в python-скрипты для обработки тяжелых многостраничных сканированных PDFов, но это вообще из другой оперы). Так вот, я подумал и решил пойти привычным инженерным путем, т.е. сделать из PSD битовый BMP, загнать его в AutoCAD и там создать некий аналог сборочного чертежа. Что-то вроде вот этого:
[http://joxi.ru/YmEy93eie3p6m6](http://joxi.ru/YmEy93eie3p6m6)
Изображение красного цвета - это "эталонный" дизайн из PSD. Сразу видно, где есть фон, а где его нет. И легко снять все необходимые размеры.
Также из Firefox я получил полный скриншот своей верстки (серый цвет на следующем изображении). Стало понятно, что моя верстка на 357 пикселей длиннее и причина видна при сопоставлении. Но есть один вопрос: для меня не понятно, по какой причине моя верстка в ширину всего 1290px, причем справа есть пустая полоска шириной 58? Вот изображение:
[http://joxi.ru/RmzYboOHQO1PrO](http://joxi.ru/RmzYboOHQO1PrO)
Если возможно, пожалуйста, дай совет, куда копать чтобы заполнить эту пустоту. Спасибо.

**Comment by nsedenkov** [comment]
> причем справа есть пустая полоска шириной 58

Разобрался - это из-за того, что у меня экран уже, чем 1300px (1280x1024), а FF выводит на скриншот только видимую часть, а все, что попадает за край экрана - заменяет пустотой. Так что данной проблемы нет, буду просто "скалывать" размеры из AutoCAD и править CSS

**Comment by kolobai** [comment]
Под соответствием дизайну я не имел ввиду попиксельное сходство (хотя бывает и такое условие) и с чертежом ты наверно перегнул. Заметил, что как минимум форма подписки в футере выглядит иначе.

Для верстки пиксель в пиксель у Firefox и Chrome есть такое расширение - Pixel perfect. Также могут помочь расширения такие как линейка MeasureIt и направляющие Ruler guides.

**Comment by nsedenkov** [comment]
Хорошо, форму в футере я проверю. Возможно, и правда упустил. Верхнее поле с товарами (featured) я вчера уже выровнял по дизайну, думаю сегодня завершу остальное, сделаю коммит и отпишусь.
PS А идею с чертежом я все же запомню, пригодится в дальнейшем.

**Comment by nsedenkov** [comment]
Главную страницу пожалуй завершил - проверил все, что только смог разглядеть. Вот фрагмент сравнения итоговой верстки с эталоном:
[http://joxi.ru/EA4KX4esjGwB2b](http://joxi.ru/EA4KX4esjGwB2b)
Что делаем дальше?

**Comment by kolobai** [comment]
Верстку на днях посмотрю.
Следующий пункт обучения, это знакомство с Javascript.
Необходимые материалы выслал на почту.

**Comment by nsedenkov** [comment]
Спасибо!

**Comment by kolobai** [comment]
Небольшие замечания по верстке.

То что нужно поправить по дизайну показал в приложенном файле.
Также для сравнения прикрепил файл с тем как дизайн выглядит у меня.

Что нужно поправить по верстке (смотрел в Firefox 46.0.1)

1. Логотип всегда является ссылкой на главную страницу.
2. При выводе рейтинга одной картинкой http://joxi.ru/8An3yJdfqaMJNr мы не сможем в дальнейшем установить другие значения.
3. Меню в футере не кликабельно http://joxi.ru/l2Z3D5bf85nw7A.

В целом очень даже хорошо. Исправляй неточности, изучай js, в следующей задаче будем добавлять интерактив.
![screenshot](https://cloud.githubusercontent.com/assets/11799289/15500726/b4594492-21b2-11e6-9856-79ddb83b4159.png)
![home](https://cloud.githubusercontent.com/assets/11799289/15500752/d76a0098-21b2-11e6-992e-3ade0444e236.jpg)

**Comment by nsedenkov** [comment]
Иван, спасибо за замечания! В основном все ясно, понятно, что и как исправлять. За исключением, пожалуй, полей формы логина в футере. То, что border есть только нижний - это я разглядел. А вот что делать с тем, как выглядит текст - тут затрудняюсь. Это же атрибут placeholder. Он как будто всегда полузатененный что ли. При попытке задать полям ввода цвет текста равный цвету бордера у меня в хроме визуально не изменилось ничего, тогда как в FF текст стал практически невидимым. В то время как без явного задания цвета у меня в обоих браузерах поля имеют вид, очень похожий на то, что показано в PSD. Как мне поймать данный эффект?
И еще вопрос: ты указываешь как замечание затемнении при наведении курсора на товар. Неужели не отображается? Вот мой скриншот из FF (курсор наведен на черную куртку):
![ecomm](https://cloud.githubusercontent.com/assets/12513138/15512433/96842f3c-21e8-11e6-8486-66d4f8f55478.png)
Что цена при наведении должна становиться белой, это я разглядел, исправлю. Но как же фон-затемнение и кнопка "Add to cart"? Этот эффект же не нужно делать статичным, только на ремне, как показано в дизайне? Или нужно? Я сделал через hover:
`.shop-item:hover {
    background-color: rgba(100, 117, 159, 0.3);
}
`
и
`.shop-item:hover .add-cart-button {
    display: inline-block;
}
`
Это не верно?

**Comment by nsedenkov** [comment]
Сам добавлю одно замечание: в IE11 секция Subscribe смещается к левой границе окна, причем заголовок и input с кнопкой остаются по центру

**Comment by nsedenkov** [comment]
Иван, а может быть, указывая на поля ввода, ты имел в виду их фон, а не цвет текста placeholder? Дело в том, что дома у меня какие-то странные цветовые настройки то ли монитора, то ли драйвера видюхи (никогда не обращал внимания, не было нужно) и за счет этого дома я глазами данного фона не вижу - все выглядит белым. Посмотрев на работе, увидел, что поля ввода имеют фон одинаковый с фоном всего футера. Может, именно фон и следует поправить?

**Comment by nsedenkov** [comment]
В последнем коммите [e2cfcd5](https://github.com/nsedenkov/mmaster_study/commit/e2cfcd5de1a90284c1a7967f32e2eed18e9697d2) исправил все, кроме бага с секцией Subscribe в IE. Также ничего не менял в плане затемнения при наведении курсора на товар (до разъяснений).

**Comment by kolobai** [comment]
1. Форма авторизации в футере

    ok

2. Затемнение
 
    В дизайне нарисовано именно затемнение, т.е. оно как бы поверх всего накладывается, а у тебя наоборот, в виде подложки.

3. Баг в IE11

    https://webref.ru/html/main - Браузеры

4. Position

    ```html
    <section class="subscr-form-sectn">
        <div class="subscr-form-bg"></div>
        <div class="subscr-form">
            <div class="subscr-form-hdr">
                <p>Subscribe to our newsletter</p>
            </div>
            <div class="subscr-form-sub-hdr">
                <p>Only our latest news to send your email address</p>
            </div>
            <form action="" method="post">
                <input type="email" id="email" name="email" placeholder="Enter your email address" required>
                <input type="submit" value="Subscribe">
            </form>
        </div>
    </section>
    ```
    Непонятно, зачем здесь манипуляции с position, если можно просто разместить один блок в другом.

4. Йд в css

    Следует отказаться от id в css селекторах, т.е. использование их для стилизации страниц нужно исключить, оставить только те, которые необходимы для работы js (на данный момент таких вроде нет).

**Comment by nsedenkov** [comment]
Иван, спасибо за комментарии, очень их ждал! По поводу IE11 я понял, он не поддерживает тэг main, следовательно странно, что "уехала" всего одна секция. Попробую заменить на обычный div и проверить в IE.
Что касается id в css - согласен, много раз об этом читал. Вот только сбил с панталыку тот парень с ютуба (ссылка в комментарии от 13.05) - он так делал, ну я и подумал, что он вероятно побольше моего соображает, раз уроки записывает. Это исправить не проблема.
А вот пункт №4 "Position" для меня пока что загадка. Сделал именно так, поскольку никак иначе не получилось. Либо наследуется opacity для всех контролов формы и они становятся еле заметными, либо получается фон выше, форма под ним (то есть выше не по z, а по y), либо фон вообще накрывает форму и контролы становятся недоступны. В итоге оставил так, поскольку вроде получил, что хотел. Если такое решение считается за ошибку, то прошу как-то намекнуть, куда копать.
Затемнение, да, сделал через background. Теперь присмотрелся - точно, ремень выглядит затемненным. Думаю, надо сделать еще один div и показывать его по hover на основном блоке. Вот только мне опять приходит в голову только position: absolute...

**Comment by nsedenkov** [comment]
Вот тут [http://weblog.west-wind.com/posts/2015/Jan/12/main-HTML5-Tag-not-working-in-Internet-Explorer-91011](http://weblog.west-wind.com/posts/2015/Jan/12/main-HTML5-Tag-not-working-in-Internet-Explorer-91011) нашел интересное решение бага с тэгом main в IE:
`main {
    display: block;
}`
И все! IE проглотил, фон секции subscribe встал на место.

**Comment by kolobai** [comment]
> А вот пункт №4 "Position" для меня пока что загадка. Сделал именно так ...

Можно использовать rgba http://htmlbook.ru/blog/poluprozrachnyy-fon.
Отправил pull request с примером.

**Comment by nsedenkov** [comment]
> Отправил pull request с примером.
Иван, спасибо, я понял - изображение фоном на всей секции, а div с rgba просто ее затуманивает. Ведь я почти так же сделал в верхней части (где барышня), а тут что-то не сообразил. Ладно, запомню.

**Comment by kolobai** [comment]
1. Цены при наведении на товар не видны, на мой взгляд их нужно расположить над блоком с тенью.
2. Йд все же стоит убрать.

Николай, на этом по этой задаче все, как закончишь, сливай эту ветку с веткой мастер, приступим к js.
