### ISSUE TITLE
Интеграция. Шаблон. Подвал. Описание и Соц сети

### ISSUE THREAD

**Issue by kolobai** [nsedenkov/mmaster_study#12]
В футер сайта нужно добавить блок с кратким описанием и блок с ссылками на соц сети. Оба блока должны иметь возможность редактирования через визуальный редактор в режиме правки.
![footer_description](https://cloud.githubusercontent.com/assets/11799289/19216280/712366dc-8dc6-11e6-97b5-518f793ed898.jpg)

**Comment by nsedenkov** [comment]
Описание - включаемая область, ссылки - кастомизированный компонент eshop-soclinks. Думал сделать компонентом, либо же просто включаемой областью с html. Посмотрел компонент и пришел к мнению, что лучше наверное так - все равно они там захардкодили непонятным образом выбранный список соцсетей, т.е захочешь добавить какой-нибудь LinkedIn - и приехали.

**Comment by kolobai** [comment]
Отлично. Можно переносить в основную ветку.

**Comment by nsedenkov** [comment]
Сделано
