### ISSUE TITLE
Карусель (слайдер) товаров

### ISSUE THREAD

**Issue by kolobai** [nsedenkov/mmaster_study#3]
Добавим карусель с товарами http://joxi.ru/5mdGZO4uvljzVr.

Нужно подобрать соответствующее решение или jQuery плагин и интегрировать его в верстку.

**Comment by nsedenkov** [comment]
Карусель на базе плагина OWL Carousel

**Comment by kolobai** [comment]
Отлично. Сливай с основной веткой.

**Comment by nsedenkov** [comment]
> Сливай с основной веткой.

Сделано
