### ISSUE TITLE
Вкладки (табы) коллекций с товарами

### ISSUE THREAD

**Issue by kolobai** [nsedenkov/mmaster_study#4]
Добавим переключение вкладок с товарами http://joxi.ru/Rmzvl01fWxqPWm.

Нужно подобрать соответствующее решение или jQuery плагин и интегрировать его в верстку.

**Comment by nsedenkov** [comment]
Переключение вкладок на базе jQuery UI

**Comment by nsedenkov** [comment]
При загрузке jquery-ui нашел способ по максимуму отключить стили, вернуло шрифт к прежнему виду, а также саму библиотеку взял по-минимуму (core, widgets, tabs)

**Comment by kolobai** [comment]
Отлично. Переноси в ветку мастер.

**Comment by nsedenkov** [comment]
Ясно, принято
