### ISSUE TITLE
Кнопка показать больше товаров

### ISSUE THREAD

**Issue by kolobai** [nsedenkov/mmaster_study#5]
Добавим динамическую подгрузку контента http://joxi.ru/12MV0OES4yvv3A.

Пускай при нажатии на кнопку "MORE" в блоке товаров появляется дополнительная строка с товарами, причем для каждой коллекции товары должны быть разные.

Подгрузку реализуем через ajax, обращаться будем к разным файлам, в зависимости от коллекции. Файлы будут содержать данные о товарах в формате json (имя, краткое описание, ссылка на изображение, цена).

**Comment by nsedenkov** [comment]
1) Загрузка товаров всегда через Ajax в рандомном порядке с учетом активной вкладки (коллекции)
2) Кнопка MORE добавляет строку (получается 9 товаров - 3 строки)

**Comment by nsedenkov** [comment]
Добавлено предотвращение повторного клика по активной вкладке

**Comment by kolobai** [comment]
Похоже php здесь тебе только помешал, так что давай пока обойдемся без него.

Первоначально на странице должно выводится товаров так же, как в дизайне, шесть штук. Затем, по нажатию на кнопку MORE, мы обращаемся к определенному, в зависимости от коллекции, файлу, содержащему информацию о товарах в формате json (тем самым мы зададим для каждой коллекции разные товары). Товары со страницы пропадать не должны, подразумевается добавление товаров на страницу, а не их замена.

**Comment by nsedenkov** [comment]
А что, наблюдается какое-либо нарушение выбора коллекции (на вкладках Mens, Womens и Kids)? Мне просто интересно, поскольку я вижу товары из разных коллекций, как и ожидал, только на вкладке All, на остальных все без сюрпризов, поскольку в items.json товары определенно помечены в поле kind. Конечно, не проблема разделить items.json на три части, просто это как будто мы к трем разным БД коннектимся. Впрочем, тут не мне судить, переделаю.
А насчет рандома и замены товаров я сам был не уверен. Теперь кажется смысл начал доходить: первоначально страница формируется на сервере и отдается клиенту, это отдельный процесс и его результат есть как бы наша статичная верстка. Далее по запросу (кнопка MORE) ajax просто доставляет клиенту дельту, не затрагивая исходный вид.
Так что, видимо помешал не php - он просто инструмент и мешать не может. Мешает недопонимание процесса. То есть, первоначально я и на "голом" js соорудил бы ровно то же самое, поскольку посчитал это неким изящным решением, что ли.
Из всего изложенного появился один вопрос: для вкладки All по нажатию кнопки MORE следует извлекать по одному товару из каждого json-файла?

**Comment by nsedenkov** [comment]
Иван, еще такая мысль: коль скоро мы стремимся к тому, чтобы при первичной загрузке присутствовали только 6 товаров, и всегда одни и те же для каждой вкладки, то мешает не тот или иной инструмент (язык), а рандом. Можно конечно "зажать" набор товаров, жестко заверстав их, как в начале? Но не правильнее ли детерминировать выборку? Мы собрались вводить id (артикулы) товаров для задачи 6, так ведь эти id нам и тут помогут + возможно какой-то признак первичности. То есть, когда первые 6 выбраны, причем каждая позиция имеет уникальное поле, и значения для шести известны, то на этапе нажатия MORE фронтэнд может сказать не "дай девять", как сейчас, когда нет полей для фильтрации, а "дай три, кроме 1-2-3-4-5-6" - и мы получим три плюсом, не трогая первые шесть. Опять же, делать можно хоть с php, хоть без него, ибо дело в самой логике. Как полагаешь?

**Comment by kolobai** [comment]
Есть конкретна задача, познакомится с технологией ajax, для чего в данном случае нам не нужен ответ от сервера, мы его будем имитировать путем обращения к разным файлам. 
К тому же к коду пхп также есть ряд комментариев, но так как эта задача преследует другую цель, не будем все смешивать в одну кучу.

**Comment by nsedenkov** [comment]
Ок, тогда вот так как-то. Вроде бы на сей раз все, как в тексте задачи.

**Comment by kolobai** [comment]
Николай, написал несколько комментариев к коду последнего коммита.

**Comment by nsedenkov** [comment]
Иван, большое спасибо за оперативность, а также за интересную статью с Хабра! О таком способе ничего нет ни в Codecademy, ни [в литературе](http://www.chitai-gorod.ru/catalog/book/855804/). И даже в документации jQuery нет примеров передачи в append описания элементов в объектной форме. Само собой, это куда лучше моего "топорного" способа! А по поводу коротких селекторов я в комментариях к коммиту вопрос задал, взгляни пожалуйста.

**Comment by nsedenkov** [comment]
[Исправлено и доработано](https://github.com/nsedenkov/mmaster_study/commit/4755695e74ea38f42e257a41285a7db3b3055d8c) в соответствии с комментариями к [предыдущему](https://github.com/nsedenkov/mmaster_study/commit/6b6fe06caa525afaddbff8c96e88747625474d5b) коммиту

**Comment by kolobai** [comment]
Отлично. Переноси в основную ветку.

**Comment by nsedenkov** [comment]
Перенесено в master
