### ISSUE TITLE
Корзина товаров

### ISSUE THREAD

**Issue by kolobai** [nsedenkov/mmaster_study#6]
Добавим корзину товаров и возможность добавление товара в эту корзину http://joxi.ru/E2pM8jKCBod9JA. В шапке выводим количество находящихся в корзине товаров. Через час с момента последнего добавления товара корзина должна очищаться.

Реализуем хранение данных через локальное хранилище браузера localStorage.

**Comment by nsedenkov** [comment]
Добавление в корзину заработало, автомат по удалению тоже, однако видимо немного неверно - позиции удаляются индивидуально, а не все вместе. Придется исправить.

**Comment by nsedenkov** [comment]
И да, вопрос: следует ли как-то отображать содержимое корзины?

**Comment by kolobai** [comment]
> И да, вопрос: следует ли как-то отображать содержимое корзины?

В дизайне содержимого корзины нет, следовательно нет в верстке, значит не тратим на это время, чтобы двигаться дальше, не отображаем.

И раз уж зашла речь. Не надо при выполнении работы явно добавлять что-либо от себя. Например анимация иконки количества конечно к месту, но как я уже писал, есть четкая задача, которую ты должен выполнить, так будет и в реальных задачах. Анимация и прочее согласовывается на этапе обсуждения, но это уже совсем другая история, а у нас сейчас другая цель.

> Добавление в корзину заработало, автомат по удалению тоже, однако видимо немного неверно - позиции удаляются индивидуально, а не все вместе. Придется исправить.

Да, нужно очищать корзину полностью.

**Comment by nsedenkov** [comment]
> Не надо при выполнении работы явно добавлять что-либо от себя

Анимация послужила "пробой пера" механизма замыкания для автовызова функции с некоторой периодичностью. Когда анимация получилась, стало ясно, как реализовать периодическую проверку устаревания корзины. Кстати, очищать полностью даже проще - не нужно городить городушку с проверкой каждой позиции. Вполне хватит отдельной записи со значением времени, которая будет обновляться каждый раз при добавлении в корзину новой позиции. Ее одну достаточно мониторить на предмет просрочки. Код станет проще и дружественее )))

**Comment by nsedenkov** [comment]
[Теперь](https://github.com/nsedenkov/mmaster_study/commit/2852872ae5e5eeb45fe66fef3795afd8f178eb87) корзина очищается полностью спустя час после последнего добавления позиции. Сравнение времени прямое, все излишества устранены.

**Comment by kolobai** [comment]
Код стад более понятен и это хорошо. 

Важный момент. Проверка обнуления корзины происходит при загрузке страницы и далее через час, а по условиям задачи нужно обнулять через час после последнего добавления товара.

Дополнительно инструменты для работы с корзиной можно выделить в отдельный модуль.

**Comment by nsedenkov** [comment]
> Важный момент. Проверка обнуления корзины происходит при загрузке страницы и далее через час, а по условиям задачи нужно обнулять через час после последнего добавления товара.

Секундочку! Я прямо чуть было не поверил, даже за калькулятор схватился - пересчитывать )) setTimeout принимает время в мс, следовательно следующий запуск произойдет спустя 60000 мс = 60 сек = 1 мин после загрузки страница. А вот там, где проверяется давность - там 60 * 60 * 1000 = 3600000 мс = 1 час. Как будто так и нужно. Где я не прав?

**Comment by kolobai** [comment]
Да, действительно, это работает, не доглядел. 

Но тогда другой вопрос. Допустим проверять корзину каждую минуту, для нас непозволительная роскошь. Можем ли мы здесь оптимизировать работу?

**Comment by nsedenkov** [comment]
Думаю, можно выставлять таймер на 1 час в момент добавления товара в корзину, но также каждый раз обновлять и значение времени последнего добавления. Тогда если, скажем, спустя минут 10 после первого добавления пользователь добавит еще позицию, появится новый таймер, т.е. функция очистки сработает дважды: спустя 1 час и 1 час 10 мин после первого действия, однако при первом запуске она ничего не удалит, поскольку значение времени будет обновлено в процессе добавления второй позиции, а вот при втором запуске она благополучно очистит корзину.

**Comment by nsedenkov** [comment]
И даже пожалуй [вот так](https://github.com/nsedenkov/mmaster_study/commit/d7c12f896bf9f64e43e3ec88beca82d0af83cd21), с очисткой устаревшего таймера, запуск которого заведомо бессмыслен.

**Comment by kolobai** [comment]
Логика очищения корзины работает замечательно. Но все же, лучше избавится от глобальных методов. 

https://learn.javascript.ru/global-object

Строго говоря, глобальные переменные и функции не есть хорошо в любом языке, поэтому предлагаю выделить все это в отдельный конструктор или модуль. 

https://learn.javascript.ru/constructor-new
https://learn.javascript.ru/closures-module

Нечто похожее ты уже делал.

Плюс надо учесть, что в локальном хранилище могут хранится разные данные, не только по корзине, и такой код может привести к ошибке:
```js
for (var i=0; i < localStorage.length; i++) {
    if(localStorage.key(i) != 'lastAddTime') {
        data = JSON.parse(localStorage.getItem(localStorage.key(i)));
        count += data.count;
    };
}
```

**Comment by nsedenkov** [comment]
Все, что касается работы с корзиной, выделил в модуль внутри замыкания. Постарался максимально отделить логику от обработчиков событий в main.js.
Что касается замечания про подсказки PhpStorm, то, к сожалению, единственное, что он мне "говорит" на данный момент - license expired, give me money or exit. Видимо нужно озаботиться удалить его полностью (удаление каталога .PhpStorm2016.1 в home не спасает).
Тем не менее, я проверил код [вот тут](http://jshint.com/) (Lint слишком суров, ему даже for чем-то не угодил) и устранил все замечания.

**Comment by nsedenkov** [comment]
В названии [коммита](https://github.com/nsedenkov/mmaster_study/commit/f11d8cafc0f75254f01f62241a36737c0e5e3fd7) опечатка - one key, т.е. вся корзина вместе с временем убрана в один ключ localStorage

**Comment by nsedenkov** [comment]
И сразу небольшой bugfix: несмотря на то, что js многое прощает все же правильнее проверить наличие атрибута, прежде чем обращаться к его значению.

**Comment by kolobai** [comment]
Замечательно. В мастер.

**Comment by nsedenkov** [comment]
Сделано
