### ISSUE TITLE
Битрикс. Установка

### ISSUE THREAD

**Issue by kolobai** [nsedenkov/mmaster_study#7]
Подготовимся для дальнейшей разработке.

Необходимо скачать и установить на локальном сервере последнюю версию "1С-Битрикс: Управление сайтом" редакции "Малый бизнес".

http://www.1c-bitrix.ru/download/cms.php#tab-php-link

Далее нужно удалить все лишние страницы сайта,  оставив лишь главную, а также служебные файлы и папки.

Настроить гитигнор для работы с проектом, исключив из под контроля версий папку с ядром и папку хранящую загруженные файлы.

https://git-scm.com/book/ru/v1/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B9-%D0%B2-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B9#%D0%98%D0%B3%D0%BD%D0%BE%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2

**Comment by nsedenkov** [comment]
Покопался в интернетах, нашел [вот такой](http://bx-cert.ru/advices/51/primer-fayla-gitignore-dlya-bitrix/) пример. Немного подправил под себя, получилось следующее:

> ~*
.gitignore
ecommerce/.idea/*
*.old
/upload/*
bitrix/admin/
bitrix/backup/
bitrix/cache/
bitrix/components/bitrix/
bitrix/css/
bitrix/fonts/
bitrix/gadgets/
bitrix/image_uploader/
bitrix/images/
bitrix/js/
bitrix/managed_cache/
bitrix/modules/
bitrix/otp/
bitrix/panel/
bitrix/php_interface/dbconn.php
bitrix/services/
bitrix/sounds/
bitrix/templates/.default/
bitrix/templates/eshop*
bitrix/themes/
bitrix/tools/
bitrix/tmp/
bitrix/updates/
bitrix/wizards/
bitrix/.access.php
bitrix/.settings.php
bitrix/coupon_activation.php
bitrix/footer.php
bitrix/header.php
bitrix/index.php
bitrix/license_key.php
bitrix/p3p.xml
bitrix/rss.php
bitrix/site_checker*.log
bitrix/spread.php
bitrix/urlrewrite.php
bitrix/virtual_file_system.php
bitrix/web.config

Как будто, контролю версий осталось доступно лишь то, что я могу изменить/дополнить в процессе интеграции. Я прав? Быть может, не учел что-то? Не хотелось бы засорять репозиторий лишними файлами.

**Comment by kolobai** [comment]
Здесь не надо что-то искать, надо написать конфиг самому, наша цель не копипаст.

Задача намного проще чем кажется. Нужно полностью исключить из под контроля версий папку содержащую ядро (так как вся разработка у нас будет вестись в папке local http://dev.1c-bitrix.ru/community/blogs/vad/8646.php) и папку с загруженными файлами.

**Comment by kolobai** [comment]
Задачу обсудили по почте. 
Николай, нужен наверно коммит того, к чему пришли.

**Comment by nsedenkov** [comment]
Как скажешь, Иван. Только ведь в рамках данной задачи своими руками я сделал только сам гитигнор. Остальное "прилетело" вместе с Битриксом. По условию задачи лишнее я убрал. Каталоги bitrix и uploads в игноре. Остался index.php, а также .htaccess и еще пара-тройка служебных файлов. Именно это я и смогу поместить в данный коммит - больше просто нечего. Сегодня сделаю.

**Comment by kolobai** [comment]
Николай, не хватает  файла .gitignore, в нем и состоит суть задачи.

Поясню. Вся разработка, включая интеграцию должна вестись в этом репо, т.е. он должен содержать все те же файлы что и у тебя (кроме тех, что мы условились исключить, и тех, что ты решишь добавить в игнор в дальнейшем), что бы я мог создать абсолютную копию твоего проекта.

Сейчас я в папке с репо развернул с нуля битрикс редакции "Малый бизнес", выбрав в качестве решения "Интернет магазин". Вот что у меня получилось: 

![files](https://cloud.githubusercontent.com/assets/11799289/16838187/a956d46a-49d0-11e6-8907-890013ad2616.jpg)

![git](https://cloud.githubusercontent.com/assets/11799289/16838190/b08fd24a-49d0-11e6-9d6f-2b793b721c51.jpg)

Если я сейчас я сброшу состояние к состоянию этой задачи (удалю неотслеживаемые файлы), то соответственно исчезнет в том числе и ядро, а значит сайт работать не будет. 

Надеюсь понятно описал что требуется. ) 

И еще, к этой задаче не относится, но раз уж зашла речь, на будущее. Все изменения в базе (настройки, создание/удаление/редактирование инфоблоков и прочие изменения в админке) необходимо оформлять в виде скриптов миграции (обычные php скрипты, выполняющие необходимые изменения), которые я мог бы запустить на своей копии сайта. Располагаться они должны в папке /local/migrations/, название скрипта по номеру задачи.

**Comment by nsedenkov** [comment]
Вроде понятно, Иван. Это просто по инерции получилось - сколько я видел различных гитигноров, во всех первой строкой значилось:
.gitignore
Потом уже все остальное. С этого и повелось. Буду знать, что это не всегда верно.

По поводу миграций тоже ясно (аналогичные штуки есть наверное в каждом уважающем себя фреймворке, например, в django, так что принцип уже знаком, а со спецификой как-нибудь разберемся).

**Comment by kolobai** [comment]
Удалять абсолютно все обычно нет необходимости, но здесь мы сделали это намеренно, так как в дальнейшем будем создавать самостоятельно, в целях обучения и для понимания, какой файл за что отвечает.

Сливай с основной веткой.

**Comment by nsedenkov** [comment]
Ветка 7 слита с веткой master
