### ISSUE TITLE
Интеграция. Шаблон

### ISSUE THREAD

**Issue by kolobai** [nsedenkov/mmaster_study#8]
Создадим шаблон для нашего сайта.

Необходимо создать для нового шаблона отдельную папку, куда добавить необходимые папки и файлы. В шапке и подвале разместить соответствующую html разметку, подключить стили и скрипты. Применить созданный шаблон к сайту, без каких либо условий.

Важный момент, логотип в шапке должен быть ссылкой на главную на всех страницах кроме самой главной.

![header](https://cloud.githubusercontent.com/assets/11799289/16533156/d12e4696-3fe7-11e6-86bb-f591e4d374f0.jpg)
![footer](https://cloud.githubusercontent.com/assets/11799289/16533159/d9904ac8-3fe7-11e6-8967-f7196102e0cc.jpg)

**Comment by nsedenkov** [comment]
Появился вопрос: как правильно отобразить меню, если работать только в папке local? В [учебном курсе](http://dev.1c-bitrix.ru/learning/course/index.php?COURSE_ID=43&LESSON_ID=3473&LESSON_PATH=3913.4564.4949.4708.3473) сказано: "Все шаблоны меню хранятся в папке компонента: /bitrix/components/bitrix/menu/templates/"
И если поместить шаблон как они советуют, все работает. Однако, директория bitrix у нас по условию задачи вне контроля версий, стало быть, шаблон меню в оный контроль не попадет, что плохо. Также из текста курса можно заключить, что шаблоны меню возможно размещать где-то в пределах шаблона сайта. Но любая попытка поместить шаблон меню куда-либо кроме /bitrix/components/bitrix/menu/templates/ приводит к [сообщению об ошибке](http://joxi.ru/KAxYbJRHLdBGr8). Пожалуй, можно скопировать весь компонент "Меню" в local/components, но что-то подсказывает, что данный путь неверен, поскольку компонент системный и обновляется вместе с ядром, копирование же его из обновления выключает.

**Comment by kolobai** [comment]
Здесь /bitrix/components/bitrix/{компонент}/templates/ хранятся системные шаблоны компонентов. Собственные шаблоны компонентов битрикс должны лежать в папке шаблона сайта.
http://dev.1c-bitrix.ru/learning/course/index.php?COURSE_ID=43&CHAPTER_ID=999
А в нашем случае это будет /local/templates/{шаблон_сайта}/...

Но не раз указывал, и в задаче и в письме:
>  в рамках этой задачи не нужно интегрировать компоненты (меню и прочее), только создать шаблон и разместить в нем html разметку. Интегрировать компоненты будем после, каждый в отдельности.

При чем здесь сейчас меню?

**Comment by nsedenkov** [comment]
Ясно, спасибо, Иван! Действительно, в письме от 08.07 такая фраза есть. Тогда видимо данный этап будет немного проще. Постараюсь сегодня сделать коммит, поскольку статику и стили Битрикс уже показывает, осталось добавить скрипты (вчера просто с этим самым меню провозился).

**Comment by nsedenkov** [comment]
[Вот](https://github.com/nsedenkov/mmaster_study/commit/3147ffb3348f393a64a39aff62aa035b5ed7d6e9): шапка (узкая, без картинок), подвал, нужные для них стили и скрипты (функционал корзины работает - красный круг с цифрой не виден, поскольку в localstorage пусто)

**Comment by kolobai** [comment]
#### Включениям php в html:

1. Пробелы и короткий оператор echo. 

    до
    ```php
    <?echo SITE_TEMPLATE_PATH?>
    ```
    после
    ```php
    <?= SITE_TEMPLATE_PATH ?>
    ```

2. Альтернативный синтаксис управляющих структур http://php.net/manual/ru/control-structures.alternative-syntax.php

    до
    ```php
    <div class="logo">
        <?if($_SERVER["REQUEST_URI"] != '/'){?><a href="/"><?}?>
            <img src="<?echo SITE_TEMPLATE_PATH?>/images/logo.png">
        <?if($_SERVER["REQUEST_URI"] != '/'){?></a><?}?>
    </div>
    ```
    после
    ```php
    <div class="logo">
        <? if ($_SERVER["REQUEST_URI"] != '/'): ?>
            <a href="/">
        <? endif; ?>
                <img src="<?= SITE_TEMPLATE_PATH ?>/images/logo.png">
        <? if ($_SERVER["REQUEST_URI"] != '/'): ?>
            </a>
        <? endif; ?>
    </div>
    ```

#### По использованию API:

1. От использования глобальных переменных сервера по возможности стоит отказаться

    ```php
    <? if ($_SERVER["REQUEST_URI"] != '/'){ ?><a href="/"><? } ?>
    ```
    Большинство, что тебе может понадобится, можно получить через API
    http://dev.1c-bitrix.ru/api_help/main/reference/cmain/index.php
    http://dev.1c-bitrix.ru/api_d7/bitrix/main/server/index.php
    http://dev.1c-bitrix.ru/api_d7/bitrix/main/request/index.php

2. Если твоя IDE дает подсказки в формате PhpDoc, то ты можешь подключить эту библиотеку https://github.com/matiaspub/bxApiDocs и заметить один устаревший метод в коде. Также эту библиотеку можно использовать для работы автодополнения кода, отключив при этом индексацию фалов ядра, чтобы не нагружать IDE.

**Comment by nsedenkov** [comment]
Ясно, поправим. Кстати, и про короткий оператор echo, и про альтернативный синтаксис было в уроках codecademy. Короткий echo (как и короткий открывающий тэг) мне почему-то визуально не сильно нравятся. Будь моя воля, я бы вообще написал
```php
<?php echo SITE_TEMPLATE_PATH ?>
```
Однако короткий открывающий тэг Битрикс по сути навязывает, так что придется привыкать к краткости во всем )))

А вот альтернативный синтаксис - в этом примере совершенно согласен, выглядит куда читабельнее, чем скобочки между знаками вопроса. Грешен, подзабыл про такую форму записи. Исправлю.

Насчет $_SERVER я и сам сомневался, ибо уже почти дочитал в учебном курсе о ядре D7 - начиная с раздела "Приложения и контекст" становится ясно, что все, что берется из $_SERVER , $_ENV, $_REQUEST Битрикс отдаст через свои функции. Однако засомневался, поскольку не раз встречал обращение к $_SERVER[что-то-там] в примерах того же учебного курса. Собственно, и ожидал получить рекомендацию на сей счет, за что спасибо, учту.

**Comment by kolobai** [comment]
Николай, ты совершенно прав, короткие теги <? использовать не рекомендуется, но в шаблонах системных компонентов таких конструкций полно, так что здесь можешь делать на свое усмотрение.

Еще, что удалось заметить, если ты используешь версию php >= 5.4, то есть новый синтаксис массивов http://php.net/manual/ru/migration54.new-features.php.

И дополнительно, в рамках задачи, не плохо было бы добавить скрипт миграции - применение нового шаблона.

**Comment by nsedenkov** [comment]
Скрипт миграции - это есть хорошо! Отличный повод начать разбираться с данным вопросом!

**Comment by kolobai** [comment]
Официального инструмента миграции у битрикс нет (давно обещали сделать), есть некоторые модули и библиотеки сторонних разработчиков, но так как они к обучению косвенно относятся, можно оформлять просто, в виде страниц, размещая на этих страницах кнопки для запуска миграции и вывод информации о результате работы скрипта.

**Comment by nsedenkov** [comment]
> Официального инструмента миграции у битрикс нет

И почему я не удивлен? )))

Ладно, это ничего. Думаю, главное, чтобы в API были нужные функции (пока не подсказывай, сам покопаюсь)

**Comment by nsedenkov** [comment]
Иван, взгляни пожалуйста - подойдет ли такая штука в качестве скрипта миграции, или слишком вычурно? Честно, не хотелось хардкодить имя шаблона, заодно какая-никакая проверка, что шаблон существует (хотя я убедился, что сам Битрикс не проверяет состав шаблона, по его мнению если есть папка внутри templates - то есть и шаблон с именем папки, то есть пустая папка тоже применяется в качестве шаблона через админку битрикса, поэтому в скрипте я также не стал заморачиваться на проверку, что внутри папки лежит нечто, похожее на шаблон).

**Comment by kolobai** [comment]
Николай, здесь не нужен интерфейс выбора шаблона :), а нужен скрипт с конкретными изменениями в БД средствами API, в данном случае применение шаблона, созданного тобой в результате разработки.

> Миграции - это что-то вроде системы контроля версий для вашей базы данных. Они позволяют команде программистов изменять структуру БД, в то же время оставаясь в курсе изменений других участников.

Давай условимся, на странице должно быть только три блока:
- название миграции (что делает)
- кнопка применить
- результат выполнения

**Comment by nsedenkov** [comment]
Вот поэтому я говорю - может быть, слишком вычурно? Стало быть, так и есть. Посмотри пожалуйста скрипт в задаче 9: там нечего выбирать, нужно было просто создать инфоблок и разделы в нем. Там выглядит и работает практически в точности по указанным трем пунктам. Это ближе к истине?

**Comment by nsedenkov** [comment]
[Применил](https://github.com/nsedenkov/mmaster_study/commit/58695a75a1f08f28328b341fc024c6054af12625) рекомендацию по фигурным скобкам. Для себя определил так: если много html с малыми вкраплениями php - отдавать предпочтение альтернативному синтаксису (if - endif и т.п.), в случае же, когда в файле преобладает php-код - использовать фигурные скобки. Согласен, так текст скрипта выглядит правильнее.

**Comment by kolobai** [comment]
Отлично, добавляем в основную ветку.

**Comment by nsedenkov** [comment]
Сделано
