### ISSUE TITLE
Интеграция. Шаблон. Шапка. Меню

### ISSUE THREAD

**Issue by kolobai** [nsedenkov/mmaster_study#9]
Добавим на сайт меню.

Необходимо с помощью стандартных компонентов реализовать вывод меню в шапке. Меню должно строится на основе разделов каталога. Ссылки в меню должны быть человеко-понятными (ЧПУ) и вести на реальные страницы, для чего необходимо создать страницу каталога, разместить и настроить на ней компонент каталог, в качестве вида каталога можно использовать стандартный шаблон.

![menu](https://cloud.githubusercontent.com/assets/11799289/16839080/c6477782-49d5-11e6-8d83-31bbcd4fc546.jpg)

**Comment by nsedenkov** [comment]
Скрипт создания инфоблока с разделами + шаблон меню
Остался непонятен один момент: при залогиненном админе меню выводится нормально, при анонимном пользователе сбиваются ссылки (инфоблок после [исправления](https://github.com/nsedenkov/mmaster_study/commit/85da2c9ed6e7371c4fb4c51741dcb72668968feb) доступен на чтение для неавторизованных пользователей)

**Comment by nsedenkov** [comment]
>Остался непонятен один момент: при залогиненном админе меню выводится нормально, при анонимном пользователе сбиваются ссылки

Данный баг не воспроизводится - ссылки выставляются нормально. Это был видимо кэш браузера (или самого битрикса)

**Comment by kolobai** [comment]
Общее впечатление от кода, что очень много в нем лишнего, вместе с разным стилем оформления это делает его трудным к восприятию и дальнейшей его поддержке. 
https://github.com/getjump/fig-standards/tree/master/accepted

Меню сделано не по стандартам битрикс. 
https://dev.1c-bitrix.ru/learning/course/?COURSE_ID=43&LESSON_ID=3498

PS Меню у меня не заработало, йд не совпали.
https://github.com/nsedenkov/mmaster_study/commit/85da2c9ed6e7371c4fb4c51741dcb72668968feb#commitcomment-18310626

**Comment by nsedenkov** [comment]
В смысле, id инфоблока? Так и думал. Именно этот хардкод id меня сейчас и беспокоит. Он же никогда не совпадёт без ручной правки, а ручная правка ломает саму идею разворачивания из git! Собираюсь на выходных попытаться найти решение.

**Comment by nsedenkov** [comment]
Ага, нашел твою подсказку в коммите, спасибо! (смотрю с телефона, не сразу все замечаю на узком экране)

**Comment by nsedenkov** [comment]
Привел меню (как мне представляется) к стандартам. Скрипт миграции дополнил созданием типа инфоблоков "Блог" и собственно инфоблока "Блог" для вывода соответствующего пункта меню. Также постарался исправить стиль оформления в соответствии с рекомендациями из статьи. Что считать в скрипте лишним - тут даже предположить затруднюсь. Разве что проверку состояния успех/ошибка после каждой операции? Кроме этого там собственно и нет ничего...
Что не получилось:
1) Избавиться от хардкода ID инфоблока. При попытке указать код инфоблока (нечто вроде
```php
"CODE" => "catalog"
```
меню просто пропадает, а на странице появляется надпись "раздел не найден". Возвращаю вызов по ID - все нормально. Также поступив по рекомендации учебника и поместив на страницу компонент "Каталог" в визуальном редакторе, не нашел в сформированном массиве никаких упоминаний о коде инфоблока - только ID.
2) Сократить вызов \Bitrix\Main\Context::getCurrent()
При написании согласно мануалу по неймспейсам
```php
use function \Bitrix\Main\Context\getCurrent as getCurrentContext;
```
или так
```php
use \Bitrix\Main;
use function Main\Context\getCurrent as getCurrentContext;
```
после обращения к такому псевдониму пишет
"Fatal error: Call to undefined function bitrix\main\context\getcurrent()"
Возможно, из-за того, что метод статический? Иных идей пока не имею.

**Comment by nsedenkov** [comment]
Иван, способ подключить блок без хардкода его ID я придумал. Возможно, это костыль, но он работает. Теперь подумаю над неймспейсами.

**Comment by nsedenkov** [comment]
Вроде разобрался с импортами. Импортировать нужно класс, а не отдельный метод. Собственно, как и почти везде (в питоне можно импортировать полностью модуль, а потом обращаться к классам через dot-notation). Сбила с толка запись в мануале вида
```php
use function \Path\To\Any\Function;
```
Видимо, имеется в виду импорт отдельной функции в пределах неймспейса, но к методам класса (хоть статическим, хоть нет) это неприменимо.

**Comment by kolobai** [comment]
Николай, картина после последнего моего комментария не сильно изменилась:

1. В файле .top.menu.php лишний код, попробуй отредактировать меню в режиме правки, поймешь о чем я говорю.
2. Комментарии к скрипту миграции те же, нам необходимо сделать простые действия, а твой код слишком перегружен циклами и условиями.

И ссылка blog пусть ведет на обычную страницу, как home, здесь не нужен инфоблок.

**Comment by nsedenkov** [comment]
> В файле .top.menu.php лишний код, попробуй отредактировать меню в режиме правки, поймешь о чем я говорю.

Собственно, вариантов немного ))) Пролистав снова страницы курса разработчика, посвященные созданию меню, пришел к мнению, что в этом файле ВЕСЬ код лишний, кроме собственно объявления массива. Ведь в данном файле не подключаются никакие компоненты и вообще нет вызовов API. Так зачем проверять, подключен ли пролог и доступны ли инфоблоки? Все проверки логично сделать в файле .top.menu_ext.php, ведь там как раз присутствуют вызовы API. Верно мыслю?
Однако, редактирование в режиме правки все же сделаю. Любопытно, что скажет Битрикс.

**Comment by nsedenkov** [comment]
Вот же, вместо preview нажал Close ... Хорошо хоть Reopen предусмотрен. Да, надо отдыхать иногда )))

**Comment by nsedenkov** [comment]
[Исправил](https://github.com/nsedenkov/mmaster_study/commit/009405dc66ab24ff6ad1d5b5d936d848b487e3fe) файлы сборки меню, убрал инфоблок блога, еще упростил скрипт миграции (в секции собственно создания блока и разделов остался один цикл - при создании разделов, иначе в данном месте получится совсем по-индусски)

**Comment by kolobai** [comment]
1. http://nsedenkov.loc/catalog/Mens/ url обычно всегда в нижнем регистре.
2. Нет возможности редактирования меню в режиме правки http://joxi.ru/vAWVwJbSkvk8z2
3. Нет возможности изменить ссылку Blog. Можно это как то обыграть?

**Comment by nsedenkov** [comment]
По замечанию 2: похоже, помог режим совместимости с ЧПУ в menu.sections: [http://joxi.ru/nAyYbJ3HdzLVAZ](http://joxi.ru/nAyYbJ3HdzLVAZ) (коммит с данным изменением пока не делаю - решу сразу и №3)

**Comment by nsedenkov** [comment]
Пункты Home и Blog можно менять в редакторе. Позиция для вставки дополнительных пунктов указывается в параметрах компонента, по умолчанию 1 - после первого статичного пункта. Таким образом, если указать например 0, то порядок будет "Mens Womens Kids Home Blog"

**Comment by nsedenkov** [comment]
Чуть больше контроля: если враг установит значение EXT_LINKS_POS большим, чем количество статичных пунктов, произойдет сброс к значению по умолчанию, т.е. 1

**Comment by kolobai** [comment]
Отлично, задау можно переносить и закрывать.

**Comment by nsedenkov** [comment]
Сделано
